var _tmr=_tmr||[];
(function(){function v(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function C(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function cb(a){return null===a.offsetParent||0==a.offsetHeight||0==a.offsetLeft||0==a.offsetTop||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth?!1:void 0===e.getComputedStyle?(a=e.getComputedStyle(a,null),"none"!=a.getPropertyValue("display")&&"hidden"!=a.getPropertyValue("visibility")):
!0}function R(a,b){for(var c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function $(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function ma(){var a=arguments,b=a[0]||{},c=!1,d=1,h=a.length,k,f,u,g,e;"boolean"===typeof b&&(c=b,b=a[d++]||{});for($(b)||(b={});d<h;d++)if(null!=(k=a[d]))for(f in k)u=b[f],g=k[f],b!==g&&(c&&g&&($(g)||(e="[object Array]"===Object.prototype.toString.call(g)))?(e?(e=!1,u=u&&"[object Array]"===Object.prototype.toString.call(u)?
u:[]):u=u&&$(u)?u:{},b[f]=ma(c,u,g)):void 0!==g&&(b[f]=g));return b}function Aa(a){var b="";try{var c=new Uint8Array(a);e.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(h){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function p(){return(new Date).getTime()}function x(a,b){var c={data:b,raw:a,url:"https://top-fwz1.mail.ru"+a};if(void 0===b)c.dataSplitter=";",c.open=db,c.connect=eb,c.startListen=fb,c.stopListen=gb,c.open(c),c.connect(c);
else{var d;"function"===typeof e.XMLHttpRequest?(c.dataSplitter=";",c.open=hb,c.connect=ib,c.startListen=jb,c.stopListen=kb,c.open(c),c.connect(c),d=!0):d=!1;d||lb(c)}}function lb(a){var b=g.createElement("iframe"),c=g.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);g.body.appendChild(c);try{var d=b.contentWindow.document,h=d.createElement("div"),k;for(k in a.data)if(a.data.hasOwnProperty(k)){var f=
a.data[k],u=typeof f;if("string"===u||"number"===u){var e=d.createElement("input");e.setAttribute("type","hidden");e.setAttribute("name",k);e.value=f;h.appendChild(e)}}var l=d.createElement("form");l.setAttribute("action",a.url);l.setAttribute("method",Ba);l.setAttribute("enctype",Ca);l.appendChild(h);var p=d.createElement("div");p.appendChild(l);d.body.appendChild(p);var n=function(){try{C(b,"load",n),g.body.removeChild(c)}catch(a){m&&console.warn("[TopMailRu] Error#1.2",a)}};v(b,"load",n);l.submit()}catch(r){m&&
console.warn("[TopMailRu] Error#1.3",r)}}function hb(a){a._connection=new e.XMLHttpRequest}function ib(a){a._connection.open(Ba,a.url);a._connection.setRequestHeader("Content-Type",Ca);a._connection.send(na(a.data,a.dataSplitter))}function jb(a){v(a._connection,"load",a._onload);v(a._connection,"error",a._onerror)}function kb(a){C(a._connection,"load",a._onload);C(a._connection,"error",a._onerror)}function db(a){a._connection=new Image}function eb(a){a._connection.src=a.url+na(a.data,a.dataSplitter)}
function fb(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function gb(a){a._connection.onload=null;a._connection.onerror=null}function na(a,b){var c=b||";",d="",h;for(h in a)if(a.hasOwnProperty(h)){var k=a[h],f=typeof k;if("string"===f||"number"===f)d+=c+escape(h)+"="+escape(k)}return d}function aa(a){return(a=g.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function K(a,b,c){c=c||{};var d=c.expires;
"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var h in c)if((b=c[h])||0===b)a+="; "+h,!0!==b&&(a+="="+b);g.cookie=a}function mb(){var a="tmr"+(""+Math.random()).slice(2);try{return L=e.localStorage||null,L.setItem(a,a),L.removeItem(a),!0}catch(b){return L=null,m&&console.warn("[TopMailRu] Error#1.4",b),!1}}function nb(){if(!ba)return null;for(var a=w.hostname.split(".").reverse(),b,c=1,
d=a.length;c<d;c++){b=a[0];for(var h=1;h<=c;h++)b=a[h]+"."+b;var h=""+p(),k={domain:b,path:"/",expires:3E5};try{K("tmr_tcdhn",h,k);var f=aa("tmr_tcdhn"),k=k||{};k.expires=-1;K("tmr_tcdhn","",k);if(f===h)return b}catch(g){m&&console.warn("[TopMailRu] Error#1.8",g)}}return null}function ca(a,b){ba&&K(a,b,Da);if(oa)try{L.setItem(a,b)}catch(c){m&&console.warn("[TopMailRu] Error#1.6",c)}}function pa(a){var b;if(!(b=ba?aa(a):null)){var c;if(oa)a:{try{c=L.getItem(a);break a}catch(d){m&&console.warn("[TopMailRu] Error#1.5",
d)}c=null}else c=null;b=c}return b}function Ea(a){var b=";e="+escape("detect");x(s(a,"/tracker",!1,!1)+b)}function Fa(a,b){if(a.length&&null!==b.ecom_data){var c=S(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=qa("_m",b.ecom_method),h=qa("_t",b.ecom_type),k=qa("_jst",Ga()),c="{"+c+d+h+k+"}";x(s({id:a[0]},"/datalayer",!1,!1)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function qa(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+
'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function ob(){var a=aa(Ha);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=p()-b;return 0>b||b>Ia?null:{id:a[0],version:a[1]}}function l(){}function T(a){a&&"object"===typeof a&&(!D&&"id"in a)&&(D=a.id)}function pb(a){return(a=!F?void 0:F[a])&&ra?a-ra:void 0}function Ja(){if(F){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<
b.length;c++){var d=!F?void 0:F[b[c]];if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function U(a){return a&&"object"===typeof a&&("id"in a&&a.id||D)}function s(a,b,c,d){ca(sa,++M);var h="id"in a?a.id:D,k="url"in a?a.url:w.href,f="referrer"in a?a.referrer:g.referrer,u="title"in a?a.title:g.title,l;l=ta;null===l&&(l=qb());l=null!==l?l?1:0:null;var q="userid"in a?a.userid:z||0===z?z:void 0,v=H?H:void 0,n;n=[];D&&h!==D&&n.push("sec");"dataLayer"in e&&n.push("dl");B&&n.push(["ecom"].concat(B).join("-"));
var r=rb();r&&r.length&&n.push(["jst"].concat(r).join("-"));n=n.join(",");var t=e.screen,y,r=(new Date).getTimezoneOffset();y="";if(e.Intl)try{y=e.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(sb){m&&console.warn("[TopMailRu] Error#1.1",sb)}y=r+"/"+y;r=Ka;r=null!==r?r:ob();a.start=Ja();b=b+"?js=13"+(h?";id="+escape(h):"")+(k?";u="+escape(k):"")+(f?";r="+escape(f):"")+(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+
("pid"in a?";pid="+escape(a.pid):"")+(void 0!==q?";userid="+escape(q):"")+(void 0!==v?";uparams="+escape(S(v)):"")+(d&&u?";title="+encodeURIComponent(u):"")+(t?";s="+t.width+"*"+t.height:"")+";vp=";h=d=0;g.documentElement&&(g.documentElement.clientWidth||g.documentElement.clientHeight)?(d=g.documentElement.clientWidth,h=g.documentElement.clientHeight):"number"==typeof e.innerWidth&&(d=e.innerWidth,h=e.innerHeight);b=b+(""+d+"*"+h)+";touch="+tb+";hds="+ub+";frame="+vb+";flash=";if(null===V)if(V="",
G.plugins&&G.plugins["Shockwave Flash"])V=G.plugins["Shockwave Flash"].description.split(" ")[2];else if(e.ActiveXObject)try{var A=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),A=A.GetVariable("$version"),A=A.split(" ")[1].split(",");V=A[0]+"."+A[1]}catch(wb){m&&console.warn("[TopMailRu] Error#1.12",wb)}A=b+V+";sid="+La+";ver="+Ma+";tz="+encodeURIComponent(y);if(c){if(!F||!ua)c="";else{c=[];c.push(ua.type);c.push(ua.redirectCount);c.push(ra);for(b=0;b<Na.length;b++)c.push(pb(Na[b]));c=c.join("/")}c=
";nt="+c}else c="";c=A+c+("device"in a?";device="+escape(a.device):"")+";ni=";if(!G||!G.connection)A="";else{A=G.connection;b=[];for(h=0;h<Oa.length;h++){d=A[Oa[h]];if(void 0!==d)switch(d){case !0:d=1;break;case !1:d=0;break;default:d=(""+d).replace(/\//g,"_")}b.push(d)}A=b.join("/")}return c+A+("params"in a?";params="+escape(S(a.params)):"")+(null!==l?";detect="+l:"")+(ba||oa?";lvid="+escape([W,p(),M,N].join(":")):"")+(n?";opts="+escape(n):"")+(r?";flocid="+escape(r.id)+";flocv="+escape(r.version):
"")+("version"in a?";appver="+escape(a.version):"")+(O.support?";visible="+O.getValue():"")+";_="+Math.random()}function Pa(a){a=";e="+escape("PVT/"+a);for(var b=0;b<t.length;b++)x(s(t[b],"/tracker",!1,!0)+a)}function xb(){ta=!0;Qa(1);if(!Ra&&!X){X=!0;for(var a=0;a<t.length;a++)Ea(t[a])}}function yb(){Qa(0);ta=!1}function qb(){var a=aa(Sa);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=p()-b;if(0>b||b>Ta)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function Qa(a){var b=
p();a=[a,b].join("|");K(Sa,a,{path:"/",expires:Ta})}function da(){g.addEventListener?(C(g,"DOMContentLoaded",da),_tmr.onready()):g.attachEvent&&"complete"===g.readyState&&(C(g,"readystatechange",da),_tmr.onready())}function Ua(){C(e,"load",Ua);_tmr.onready();_tmr.onload()}function ea(){C(e,"unload",ea);C(e,"beforeunload",ea);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var e=window,G=navigator,g=document,w=location,Y="string"===typeof w.hostname?w.hostname:"",fa=-1!=Y.search(/(^|\.)odnoklassniki\.ru$/)||
-1!=Y.search(/(^|\.)ok\.ru$/),ga=-1!=Y.search(/(^|\.)vk\.com$/),zb=-1!=Y.search(/(^|\.)lamoda\.ru$/),Ab=-1!=Y.search(/(^|\.)kommersant\.ru$/),Bb="string"===typeof w.search&&-1!=w.search.search(/[?&]rb_clickid=/),m="string"===typeof w.search&&-1!=w.search.search(/[?&]tmr_debug=1(?:&|$)/),Va=fa||ga||zb||Ab,Cb=!Bb,Db=fa||ga,Eb=fa||ga,Wa=fa||ga,Ra=!1,S=e.JSON&&JSON.stringify?JSON.stringify.bind(JSON):function(a){return""},Ba="POST",Ca="application/x-www-form-urlencoded",ba=!(0===w.hostname.search(/^(\d+.)+\d+$/g)||
-1!==w.hostname.search(/:/g)),L=null,oa=mb(),Da={domain:nb(),path:"/",expires:287712E5};(function(){var a;if(a=g.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,h=a.length;d<h;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){b=0;for(d=a.length;b<d;b++)h=a[b][0],c=Da||{},c.expires=-1,K(h,"",c)}})();var X=!1,ta=null,Ta=864E5,Sa="tmr_detect",Fb=function(){function a(a,b){for(var c=a.length,f,g,e=0;e<b;e++)g=Math.floor(Math.random()*
c),f=a[e],a[e]=a[g],a[g]=f;return a.slice(0,b)}function b(b,h){var k=g.createElement("div"),f=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,
103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,
101,114,45,98,108,111,99,107).split(" "),f=a(f,c);k.setAttribute("class",f.join(" "));k.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");k.setAttribute("id","trg-b-banners-1");k.setAttribute("data-view","SlotView.mimic");this.bait=g.body.appendChild(k);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;
this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=h||null;var e=this;setTimeout(function(){e._checkBait.call(e)},1)}var c=7;b.prototype._checkBait=function(){if(X)this._stop();else{var a=null!==g.body.getAttribute("abp")||!cb(this.bait);(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){m&&console.warn("[TopMailRu] Error#1.9",c)}else if(!a&&10>this.loopNumber){var f=this;setTimeout(function(){f._checkBait.call(f)},50*this.loopNumber)}else try{b=
this.fnNegative,b()}catch(e){m&&console.warn("[TopMailRu] Error#1.10",e)}}};b.prototype._stop=function(){try{g.body.removeChild(this.bait)}catch(a){m&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),B=null,Xa="ecommerce",E="dataLayer",P=null,va=!1,ha=[],Gb=[36383,2540645,3171181,3074137,2057653],Hb=[],wa;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var h={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},
f=0,g=b.length;f<g;f++){var k=y[b[f]];if(k){a(h.ecom_method,[b[f]]);for(var e=0,l=k.length;e<l;e++)for(var u=0,n=d.length;u<n;u++){var m=k[e][d[u]];if(m)for(var p=0,r=c.length;p<r;p++)if(-1!==k[e].type.indexOf(c[p])){a(h.ecom_type,[c[p]]);a(h.ecom_data.events,m);break}}}}return h}function c(a,b,c){if(!a||!c||!(b in y))return null;for(var d,h=0,f=y[b].length;h<f;h++)if(d=y[b][h],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=
[],f,e,n=0,y=a.length;n<y;n++)if(e=a[n]){f=null;try{if(e.ecommerce)f=h(e)||k(e);else if(null===e.ecommerce)f=null;else if(e.event){var q={event:e.event,ecommerce:{}};f=h(q)||k(q)}else if("event"===e[0]){var v=e[1],x=e[2],w=c(v,l,r);w&&(w.ecom_data[v]=x);f=w}else if(e.event===Xa)a:{for(var s=b([g],[p],[t]),z=0,C=s.ecom_data.events.length;z<C;z++)if(!e.hasOwnProperty(s.ecom_data.events[z])){f=null;break a}delete s.ecom_data.events;s.ecom_data[Xa]=e;f=s}}catch(D){m&&console.warn("[TopMailRu] Error#1.23",
D),f=null}f&&(d.push(f),ha.push(f))}if(d.length){a=0;for(f=d.length;a<f;a++)Fa(ia,d[a]);B||(B=[0,0,E]);B[0]+=d.length;f=a=0;for(n=d.length;f<n;f++)a+=S(d[f].ecom_data).length;B[1]+=a}}function h(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&(b=c(d,g,q))){if(a.event&&(d=c(a.event,g,n)))for(var f=0,h=b.ecom_type.length;f<h;f++)-1===d.ecom_type.indexOf(b.ecom_type[f])&&(b.ecom_type.splice(f,1),h--,f--);b.ecom_data=a.ecommerce;return b}return null}function k(a){var b=a.event,d=c(b,
g,n);d&&(d.ecom_data[b]=a.ecommerce);return d}function f(a){if((a=e[a])&&"function"===typeof a.push)d(a),P=a.push,a.push=function(){var a=P.apply(this,arguments);d([].slice.call(arguments,0));return a}}var g="push",l="gtag",p="gse",q="inner",n="outer",r="external",t="required",y={};y[l]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},
{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];y[g]=[{type:[p],required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([l],["ga4"],[r]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},
{type:["ym","gee"],inner:["add","detail","purchase","remove"]}];wa=function(a){if(!(a===E&&P)){a!==E&&(ha=[]);var b=e[E];b&&"function"===typeof b.push&&P&&(b.push=P,P=null);f(a);va=!0}}})();var Ga=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;try{c=Object.keys(e).join(",")}catch(d){c=null}for(var h=
[],k,f=0,g=a.length;f<g;f++){k=b[a[f].id];if(void 0===k)a:{k=a[f].globalVars;for(var l=c,m=0,p=k.length;m<p;m++){var n=k[m];if("string"===typeof n&&!(n in e)||"string"===typeof n.re&&(l&&-1===l.search(RegExp("($|,)"+n.re+"(,|^)","m"))||1===p)){k=!1;break a}}k=!0}k&&(b[a[f].id]=!0,R(a[f].id,h)||h.push(a[f].id))}return h}}(),rb=Ga,Ia=864E5,Ha="tmr_floc",Ka=null;(function(a){try{g.interestCohort&&"function"===typeof g.interestCohort&&g.interestCohort().then(function(a){Ka={id:a.id,version:a.version};
a=[a.id,a.version];var b=p();a=a.concat(b).join("|");K(Ha,a,{path:"/",expires:Ia})},function(){})}catch(b){}})();var O={support:!1},O=function(){function a(){d(k)}function b(){d(k,t)}function c(){return f?!g[f]:null}function d(a,b){var d=p(),f="undefined"===typeof b?c():b;if(null===n[a])n[a]={ts:d,state:f,total:0};else{var e=n[a];if(e.state!==f){var k=d-e.ts,g=e.state;e.ts=d;e.state=f;k<h||(g===m?(e.total+=k,r&&r(d,k)):g===q&&s&&s(d,k))}}}var h=5,k="auto",f=null,l=null,m=!0,q=!1,t=null;"hidden"in
g?(f="hidden",l="visibilitychange"):"mozHidden"in g?(f="mozHidden",l="mozvisibilitychange"):"webkitHidden"in g?(f="webkitHidden",l="webkitvisibilitychange"):"msHidden"in g&&(f="msHidden",l="msvisibilitychange");var n={};n[k]=null;var r=n.user=null,s=null;return{support:!!f,auto:function(c,d){r=c||null;s=d||null;f&&(a(),v(g,l,a));v(e,"beforeunload",b);v(e,"unload",b)},set:function(a){d("user",!!a)},getLog:function(){var a=p(),b={},c,d;for(d in n)c=n[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},
getValue:c}}();O.auto();var Ma="60.3.0",xa=0,ja=0,La=Aa(16),z=null,H=null,ka=0,sa="tmr_reqNum",M=pa(sa),M=null===M?0:parseInt(M,10);ca(sa,M);var N=pa("tmr_lvid"),W=pa("tmr_lvidTS");if(null===N||-1===N.search(/^[0-9a-fA-F]+$/))N=Aa(32);ca("tmr_lvid",N);if(null===W||-1===W.search(/^\d+$/))W=""+p();ca("tmr_lvidTS",W);var D=0,t=[],ya=[],la=[],ia=[],tb="ontouchstart"in e||1<(G.maxTouchPoints||G.msMaxTouchPoints)?"1":"0",ub=e.devicePixelRatio||0,vb=e.top===e?0:1,V=null,Ya=e.performance||e.mozPerformance||
e.msPerformance||e.webkitPerformance||{},F=Ya.timing||{},ua=Ya.navigation||{},Na="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),ra=!F?void 0:F.navigationStart,Oa="downlink downlinkMax effectiveType rtt saveData type".split(" "),I,
za;I=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||D,e=c.title||null,k,f=za(b,{params:c.required,fn:c.fn});if(f.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<f.missed.length&&f.missed.slice(0,-1).join(", ")+" and "||"")+f.missed.slice(-1)+" in "+a);else{var g=za(b,{params:c.optional,fn:c.fn});k=[].concat(f.values).concat(g.values);f=[].concat(f.missed).concat(g.missed);c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?k.push("value: "+
b):f.push("value"));c=k.length?"{ "+k.join(", ")+" }":"";k=f.length?"("+(1<f.length?f.slice(0,-1).join(", ")+" and "+f.slice(-1)+" are":f.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+k):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};za=function(a,b){var c=[],d=[],e,g,f;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&!1!==b.params[e])if(g=e in a&&a[e],!0!==b.params[e]&&
(g=g||b.params[e]),g)try{f=b.fn?b.fn:null,c.push(e+': "'+(f?f(e,g):g)+'"')}catch(l){console.warn("[TopMailRu] Error#1.16",l)}else d&&d.push(e);return{values:c,missed:d}};l.prototype.callbackOnReady=function(a){m&&I("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&a.callback.call(a.context||null)};l.prototype.pageView=function(a){T(a);a:if(a&&"object"===typeof a&&a.id){5>ya.length&&!R(a.id,ya)&&(ya.push(a.id),!1!==a.beat&&la.push(a.id),t.push(a),X&&Ea(a));
var b="string"===typeof a.ecom,c=b&&-1!==a.ecom.search(/\S/);if(5>ia.length&&!R(a.id,ia)&&(!0===a.ecom||b&&!c||b&&c||!1!==a.ecom&&!b&&(R(a.id,Gb)||!R(a.id,Hb)))){ia.push(a.id);if(b&&c){if(va&&(wa(a.ecom),E!==a.ecom)){E=a.ecom;B&&(B=[0,0,E]);break a}E=a.ecom;B&&(B=[0,0,E])}b=[a.id];if(va)for(var c=0,d=ha.length;c<d;c++)Fa(b,ha[c])}}m&&I("pageView",a,{title:"Page view",optional:{url:w.href}});U(a)&&(x(s(a,"/counter",!1,!0)),ja=p())};l.prototype.reachGoal=function(a){T(a);m&&I("reachGoal",a,{title:"Reach goal",
value:!0,required:{goal:!0}});if(U(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";x(s(a,"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};l.prototype.itemView=function(a){m&&I("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(U(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0;(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||D)+"&list="+
b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");x(s(a,"/tracker",!1,!1)+(";e="+escape(b)))}};l.prototype.sendEvent=function(a){T(a);m&&I("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(U(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substring(0,
300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");x(s(a,"/tracker",!1,!1)+(";e="+escape(b)))}};l.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?m&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(z=a,m&&console.info("[TopMailRu]: Global user ID = "+
z))}};l.prototype.getUserID=function(){return z||0===z?z:void 0};l.prototype.deleteUserID=function(){z=null;m&&console.info("[TopMailRu]: Reset global user ID to null")};l.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if($(a)){try{H=ma(!0,{},a)}catch(b){m&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}m&&console.info("[TopMailRu]: Global user params = "+S(H))}else m&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};
l.prototype.getUserParams=function(){var a=H?H:void 0;return a?ma(!0,{},a):void 0};l.prototype.deleteUserParams=function(){H=null;m&&console.info("[TopMailRu]: Reset global user params to null")};l.prototype.getClientID=function(){var a=N;return a||0===a?a:void 0};l.prototype._MT_event=function(a,b,c){T(a);m&&I(b,a,{title:c});U(a)&&x(s(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+b)))};l.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};l.prototype.processEvent=
function(a,b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();
break;case "miniAppEvent":this.miniAppEvent(a)}}else m&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else m&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};l.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var Za=!1;l.prototype.onready=function(){Za||(Za=!0,!Ra&&!X&&Fb(xb,yb),wa(E))};var $a=!1;l.prototype.onload=function(){if(!$a){$a=!0;ka=p();if(!Eb&&0<t.length){for(var a=";e="+escape("RT/load")+";et="+ka,
b=0;b<t.length;b++)x(s(t[b],"/tracker",!0,!1)+a);ja=ka}Cb||setTimeout(function(){Pa(2)},2E3);Db||setTimeout(function(){Pa(15)},15E3)}};l.prototype.beat=function(){if(!Va&&xa){var a=p();if(!(12E4<a-xa)){if(12E4<a-ja)for(var b=";e="+escape("RT/resend")+";et="+ka,c=0;c<t.length;c++)!1!==t[c].beat&&x(s(t[c],"/tracker",!1,!0)+b);else 0<la.length&&x("/tracker?"+na({js:"13",id:la[0],e:"RT/beat",sid:La,ids:la.join(),ver:Ma,_:Math.random()},";"));ja=a}}};var ab=!1;l.prototype.unload=function(){if(!ab&&(ab=
!0,!Wa)){var a;a=(a=Ja())?p()-a:void 0;a=";e="+escape("RT/unload")+";et="+p()+(a?";pvt="+escape(a):"");if(O.support){var b=O.getLog();a+=";vtauto="+b.auto}for(b=0;b<t.length;b++)x(s(t[b],"/tracker",!1,!1)+a)}};l.prototype.activity=function(a){xa=p()};var Q=_tmr;_tmr=new l;for(var q=0,Z=Q.length,J;q<Z;q++)(J=Q[q])&&"object"===typeof J&&T(J);q=0;for(Z=Q.length;q<Z;q++)J=Q[q],_tmr.processEvent(J,1);q=0;for(Z=Q.length;q<Z;q++)J=Q[q],_tmr.processEvent(J,-1);if("complete"===g.readyState||"loading"!==g.readyState&&
!g.documentElement.doScroll)_tmr.onready();else g.addEventListener?v(g,"DOMContentLoaded",da):g.attachEvent&&v(g,"readystatechange",da);if("complete"===g.readyState)_tmr.onload();else v(e,"load",Ua);Wa||(v(e,"unload",ea),v(e,"beforeunload",ea));if(!Va){setInterval(function(){_tmr.beat()},6E4);try{for(var bb="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),Ib=function(a){v(g,a,function(){_tmr.activity(a)})},q=0;q<bb.length;q++)Ib(bb[q]);v(e,"scroll",function(){_tmr.activity("scallback")})}catch(Jb){m&&
console.warn("[TopMailRu] Error#1.20",Jb)}}}})();
